title: Sheepsody's Website
baseURL: "https://sheepsody.com"
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: Emacs cfg
      url: emacs/
      weight: 3
    - name: Archive
      url: archive
      weight: 3
    - name: Search
      url: search/
      weight: 3
    - name: Brain²
      url: graph
      weight: 10
    - name: CV
      url: https://github.com/Sheepsody
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  ShowToc: true
  description: "Sheepsody's Second Brain - A collection of personal notes"
  author: Victor Vialard

  defaultTheme: auto
  displayFullLangName: true
  comments: false

  homeInfoParams:
    Title: "Sheepsody's Website"
    Content: >
      Welcome to my second brain, the website where I store notes about topics I’m learning about or that I’m simply interested in.

      To browse the notes, you can either use the knowledge graph (where you will find more infos about the methods I use) or directly fuzzy-search through the index.

      If you have any remarks or anything you want to discuss, don’t hesitate to reach out to me!

  socialIcons:
    - name: Github
      url: "https://github.com/Sheepsody/MySecondBrainWebsite"
    - name: linkedin
      url: "https://www.linkedin.com/in/victor-vialard/"
    - name: email
      url: "mailto:victor.vialard@mines-paristech.fr"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
